[package]
name = "dynomite-derive"
version = "0.1.5"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Derives AWS DynamoDB dynomite types from native Rust struct types"
license = "MIT"
keywords = ["dynamodb", "rusoto"]
readme = "../README.md"
documentation = "http://lessis.me/dynomite/dynomite_derive/"
homepage = "https://github.com/softprops/dynomite"
repository = "https://github.com/softprops/dynomite"

[badges]
coveralls = { repository = "softprops/dynomite" }
maintenance = { status = "actively-developed" }
travis-ci = { repository = "softprops/dynomite" }

[lib]
proc-macro = true

[dependencies]
rusoto_dynamodb = "0.36"
dynomite = { version = "0.1.5", path = "../dynomite" }
quote = "0.6.10"
syn = "0.15.22"
proc-macro2 = "0.4"

[dev-dependencies]
tokio = "0.1"
futures = "0.1"
rusoto_core = "0.36"
uuid = { version = "0.7", features = ["v4"] }