[package]
name = "dynomite"
version = "0.1.5"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Provides type conversions between DynamoDB types and native Rust types"
license = "MIT"
keywords = ["dynamodb", "rusoto"]
readme = "../README.md"
documentation = "https://softprops.github.io/dynomite"
homepage = "https://github.com/softprops/dynomite"
repository = "https://github.com/softprops/dynomite"
edition = "2018"

[badges]
coveralls = { repository = "softprops/dynomite" }
maintenance = { status = "actively-developed" }
travis-ci = { repository = "softprops/dynomite" }

[dependencies]
failure = "0.1"
futures = "0.1"
rusoto_core = "0.36"
rusoto_dynamodb = "0.36"
uuid = { version = "0.7", features = ["v4"], optional = true }

[features]
default = ["uuid"]