[package]
name = "dynomite"
version = "0.2.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "Provides type conversions between DynamoDB types and native Rust types"
license = "MIT"
keywords = ["dynamodb", "rusoto"]
readme = "../README.md"
documentation = "https://docs.rs/dynomite"
homepage = "https://github.com/softprops/dynomite"
repository = "https://github.com/softprops/dynomite"
edition = "2018"

[badges]
coveralls = { repository = "softprops/dynomite" }
maintenance = { status = "actively-developed" }
travis-ci = { repository = "softprops/dynomite" }

[dependencies]
dynomite-derive = { version = "0.2.0", path = "../dynomite-derive", optional = true }
log = "0.4"
failure = "0.1"
futures = "0.1"
futures-backoff = "0.1"
rusoto_core = "0.36"
rusoto_dynamodb = "0.36"
uuid = { version = "0.7", features = ["v4"], optional = true }

[dev-dependencies]
env_logger = "0.6"
maplit = "1.0"
serde_json = "1.0"
tokio = "0.1"

[features]
default = ["uuid", "derive"]
derive = ["dynomite-derive"]
